export {LoginPage} from './login';
export {RegisterPage} from './register';
export {MenuPage} from './menu';
export {ChatPage} from './chat';
export {Error404Page} from './error404';
export {Error500Page} from './error500';
export {ProfilePage} from './profile';
export {ProfileChangeDataPage} from './profileChangeData';
export {ProfileChangePasswordPage} from './profileChangePassword';
